import "./globals.css";
import "../scss/index.css";
import { Raleway, Fira_Code } from "next/font/google";

const fira = Fira_Code({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-fira",
});
const raleway = Raleway({ subsets: ["latin"], variable: "--font-raleway" });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${fira.variable} ${raleway.variable}`}>{children}</body>
    </html>
  );
}
