export const ACTIONS_TYPES = {
  SEND_START: "SEND_START",
  WRONG_ENTRIES: "WRONG_ENTRIES",
  SEND_SUCCES: "SEND_SUCCES",
  EMAIL_ERROR: "EMAIL_ERROR",
  HIDE_MESSAGE: "HIDE_MESSAGE",
  HIDE_ERROR: "HIDE_ERROR",
};
